declare module "*.css"
declare module "*.woff"
declare module "*.woff2"
declare module "*.mp4"
declare module "*.svg"
declare module "*.png"
declare module "*.jpg"
declare module "*.jpeg"

declare module "intl"
declare module "intl/locale-data/*"